### ISSUE TITLE
Add clear as method instead of separate import

### ISSUE THREAD

**Issue by planttheidea** [jeromedecoster/raf-funcs#1]
Just discovered this repo, it's honestly exactly what I was looking for (`debounce` specifically, but the others are big bonuses). Was just curious if it were possible to have clear be a method on the object (like `.cancel()`) rather than a separate import. I imagine you were going for making it feel like the standard `setTimeout` and `setInterval`, and you shouldn't necessarily remove the existing usage, but the convenience function as an addition would feel much cleaner.

Happy to do a PR for it if you'd like, just wanted to make sure you were cool with the concept.

**EDIT** To clarify, I mean adding it (or a variety of it, like `.cancel()`) to `interval` and `timeout`. I noticed that in `debounce` and `throttle` you had done this exact setup, but did not do it for `interval` and `timeout`.

**Comment by jeromedecoster** [comment]
Hi,

Thanks for the idea. The initial idea was to mimic the `setTimeout` and `setInterval` with `clearTimeout` and `clearInterval`

But I make some tests with your idea and finally I think it's a good addition

I have modified the package:
- removed the `clear` function
- added the `cancel` method for `timeout` and `interval`

But also added:
- `start` method and `started` property
- `interval` has now an optional `count` property
- the `cb` of `timeout` receive now the argument `elapsed`
- the `cb` of `interval` receive now the arguments `elapsed` and `step`
